Update build_and_release.yml

diff --git a/.github/workflows/build_and_release.yml b/.github/workflows/build_and_release.yml
--- a/.github/workflows/build_and_release.yml
+++ b/.github/workflows/build_and_release.yml
@@ -17,8 +17,8 @@ on:
 jobs:
   build_wget2:
     runs-on: ubuntu-24.04
-    container:
-      image: ubuntu:rolling
+    container: "rzhy/ubuntu:wget2"
+    #      image: ubuntu:rolling
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -29,21 +29,21 @@ jobs:
           key: build-cache-x86_64-w64-mingw32-${{ github.sha }}
           restore-keys: |
             build-cache-x86_64-w64-mingw32-
-      - name: Install prerequisites
-        run: |
-          apt-get update
-          DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
-          apt-get install -y --no-install-recommends  \
-            autopoint \
-            cmake \
-            gettext \
-            gperf \
-            lzip \
-            mingw-w64 \
-            ninja-build \
-            pkg-config-mingw-w64-x86-64 \
-            git curl ca-certificates gnupg wget build-essential autoconf automake libtool python3 meson python3-pip flex texinfo jq \
-            retry
+      #- name: Install prerequisites
+      #  run: |
+      #    apt-get update
+      #    DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
+      #    apt-get install -y --no-install-recommends  \
+      #      autopoint \
+      #      cmake \
+      #      gettext \
+      #      gperf \
+      #      lzip \
+      #      mingw-w64 \
+      #      ninja-build \
+      #      pkg-config-mingw-w64-x86-64 \
+      #      git curl ca-certificates gnupg wget build-essential autoconf automake libtool python3 meson python3-pip flex texinfo jq \
+      #      retry
       - name: Compile
         env:
           CROSS_HOST: "x86_64-w64-mingw32"
@@ -69,12 +69,9 @@ jobs:
           token: ${{ secrets.GITHUB_TOKEN }}
       - name: update README.md
         run: |
-          if [[ ! -d ".git" ]]; then
-            git init
-          fi
-          cat RELEASE.md > README.md
-          git config --local user.email "actions@github.com"
-          git config --local user.name "GitHub Actions"
-          git add README.md -f  # 使用 -f 强制添加文件
-          git commit -m "更新 README 文件" --allow-empty
-          git push origin HEAD:main
+          git config --global user.email "actions@github.com"
+          git config --global user.name "GitHub Actions"
+          cp RELEASE.md README.md
+          git add README.md -f
+          git commit -m "更新 README 文件" || exit 1
+          git push origin HEAD:main || exit 1
